In [ ]:
import pandas as pd

In [ ]:

!find . -name train.csv

./train.csv


In [ ]:
df=pd.read_csv('train.csv')

In [ ]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [ ]:
###Drop Nan Values
df=df.dropna()

In [ ]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [ ]:
## Get the Dependent features
y=df['label']

In [ ]:
X.shape

(18285, 4)

In [ ]:
y.shape

(18285,)

In [ ]:
import tensorflow as tf

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
### Vocabulary size
voc_size=5000

## Onehot Representation

In [ ]:
messages=X.copy()

In [ ]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [ ]:
messages.reset_index(inplace=True)

In [ ]:
import nltk
import re
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [ ]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[2373, 4230, 238, 1201, 888, 3959, 4860, 1883, 4230, 4086],
 [3869, 2551, 1823, 4536, 3842, 940, 4038],
 [355, 56, 2439, 4899],
 [1950, 3205, 1807, 2177, 1834, 265],
 [3890, 3842, 1038, 105, 2123, 2762, 3842, 4449, 4918, 4992],
 [2936,
  1963,
  2915,
  1768,
  4282,
  4371,
  2097,
  3443,
  4176,
  2030,
  2256,
  1731,
  276,
  3161,
  4038],
 [4913, 284, 4137, 3337, 287, 3627, 2468, 1332, 619, 3334, 3675],
 [3220, 3067, 393, 941, 1532, 2462, 4371, 4054, 619, 3334, 3675],
 [2553, 4231, 4886, 4204, 783, 638, 1418, 2411, 4371, 971],
 [3095, 2015, 4710, 902, 1931, 2098, 3039, 1719],
 [1543, 2546, 4810, 547, 4290, 2416, 1051, 872, 3499, 4872, 4715],
 [2177, 663, 888, 638, 4371, 1532],
 [2178, 1702, 2430, 1987, 1422, 3630, 4654, 94, 2655],
 [2345, 700, 1341, 3951, 1297, 3112, 3896, 619, 3334, 3675],
 [2843, 1746, 2926, 4038, 3093, 619, 3334, 3675],
 [4696, 4214, 3757, 837, 1973, 1296, 3434, 2398, 806, 1603],
 [3175, 4491, 2551],
 [2165, 1178, 1786, 4393, 4371, 3424, 1428, 4038],
 [4262,

##Embedding Representation

In [ ]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)


[[   0    0    0 ... 1883 4230 4086]
 [   0    0    0 ... 3842  940 4038]
 [   0    0    0 ...   56 2439 4899]
 ...
 [   0    0    0 ...  619 3334 3675]
 [   0    0    0 ... 1185 1665 1099]
 [   0    0    0 ... 3307  908 4638]]


In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 2373,
       4230,  238, 1201,  888, 3959, 4860, 1883, 4230, 4086], dtype=int32)

In [ ]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_2 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [ ]:
len(embedded_docs),y.shape

(18285, (18285,))

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

##Model Training

In [ ]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 10s 40ms/step - accuracy: 0.7959 - loss: 0.4240 - val_accuracy: 0.9122 - val_loss: 0.1939
Epoch 2/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 8s 30ms/step - accuracy: 0.9429 - loss: 0.1455 - val_accuracy: 0.9193 - val_loss: 0.1914
Epoch 3/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9661 - loss: 0.0974 - val_accuracy: 0.9148 - val_loss: 0.2087
Epoch 4/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9731 - loss: 0.0769 - val_accuracy: 0.9100 - val_loss: 0.2597
Epoch 5/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 6s 30ms/step - accuracy: 0.9808 - loss: 0.0590 - val_accuracy: 0.9107 - val_loss: 0.2477
Epoch 6/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9837 - loss: 0.0510 - val_accuracy: 0.9147 - val_loss: 0.3197
Epoch 7/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 8s 31ms/step - accuracy: 0.9899 - loss: 0.0340 - val_accuracy: 0.9130 - val_loss: 0.3756
Epoch 8/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 10s 30ms/step - accuracy: 0.9922 - loss: 0.0271 - val_

##Adding Dropout

In [ ]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

##Performance Metrics And Accuracy

In [ ]:
# Calculate predictions
y_pred=np.argmax(model.predict(X_test), axis=-1)

189/189 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step


In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test,y_pred)

array([[3419,    0],
       [2616,    0]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.5665285832642917